/**
 * emoji-data.ts — 카테고리별 이모지 데이터 + 키워드 검색
 *
 * 약 500개 이모지를 8개 카테고리로 구성하고,
 * 영어 키워드 기반 검색 기능을 제공합니다.
 */

export type EmojiCategory = {
  name: string;
  icon: string;
  emojis: string[];
};

export const emojiCategories: EmojiCategory[] = [
  {
    name: "Smileys",
    icon: "😊",
    emojis: [
      "😀","😃","😄","😁","😆","😅","🤣","😂","🙂","😊",
      "😇","🥰","😍","🤩","😘","😗","😚","😙","🥲","😋",
      "😛","😜","🤪","😝","🤑","🤗","🤭","🤫","🤔","🫡",
      "🤐","🤨","😐","😑","😶","🫥","😏","😒","🙄","😬",
      "😮‍💨","🤥","😌","😔","😪","🤤","😴","😷","🤒","🤕",
      "🤢","🤮","🥵","🥶","🥴","😵","😵‍💫","🤯","🤠","🥳",
      "🥸","😎","🤓","🧐","😕","🫤","😟","🙁","😮","😯",
      "😲","😳","🥺","🥹","😦","😧","😨","😰","😥","😢",
      "😭","😱","😖","😣","😞","😓","😩","😫","🥱","😤",
      "😡","😠","🤬","😈","👿","💀","☠️","💩","🤡","👹",
    ],
  },
  {
    name: "People",
    icon: "👋",
    emojis: [
      "👋","🤚","🖐️","✋","🖖","🫱","🫲","🫳","🫴","👌",
      "🤌","🤏","✌️","🤞","🫰","🤟","🤘","🤙","👈","👉",
      "👆","🖕","👇","☝️","🫵","👍","👎","✊","👊","🤛",
      "🤜","👏","🙌","🫶","👐","🤲","🤝","🙏","✍️","💅",
      "🤳","💪","🦾","🦿","🦵","🦶","👂","🦻","👃","🧠",
      "🫀","🫁","🦷","🦴","👀","👁️","👅","👄","🫦","👶",
      "🧒","👦","👧","🧑","👱","👨","🧔","👩","🧓","👴",
      "👵","🙍","🙎","🙅","🙆","💁","🙋","🧏","🙇","🤦",
      "🤷","👮","🕵️","💂","🥷","👷","🫅","🤴","👸","👳",
      "👲","🧕","🤵","👰","🤰","🫃","🤱","👼","🎅","🤶",
    ],
  },
  {
    name: "Nature",
    icon: "🌿",
    emojis: [
      "🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐻‍❄️","🐨",
      "🐯","🦁","🐮","🐷","🐸","🐵","🙈","🙉","🙊","🐒",
      "🐔","🐧","🐦","🐤","🐣","🐥","🦆","🦅","🦉","🦇",
      "🐺","🐗","🐴","🦄","🐝","🪱","🐛","🦋","🐌","🐞",
      "🐜","🪰","🪲","🪳","🦟","🦗","🕷️","🦂","🐢","🐍",
      "🦎","🦖","🦕","🐙","🦑","🦐","🦞","🦀","🐡","🐠",
      "🐟","🐬","🐳","🐋","🦈","🐊","🐅","🐆","🦓","🦍",
      "🌵","🎄","🌲","🌳","🌴","🪵","🌱","🌿","☘️","🍀",
      "🍁","🍂","🍃","🪹","🪺","🍄","🌾","💐","🌷","🌹",
      "🥀","🌺","🌸","🌼","🌻","🌞","🌝","🌛","🌜","🌚",
    ],
  },
  {
    name: "Food",
    icon: "🍔",
    emojis: [
      "🍇","🍈","🍉","🍊","🍋","🍌","🍍","🥭","🍎","🍏",
      "🍐","🍑","🍒","🍓","🫐","🥝","🍅","🫒","🥥","🥑",
      "🍆","🥔","🥕","🌽","🌶️","🫑","🥒","🥬","🥦","🧄",
      "🧅","🥜","🫘","🌰","🍞","🥐","🥖","🫓","🥨","🥯",
      "🥞","🧇","🧀","🍖","🍗","🥩","🥓","🍔","🍟","🍕",
      "🌭","🥪","🌮","🌯","🫔","🥙","🧆","🥚","🍳","🥘",
      "🍲","🫕","🥣","🥗","🍿","🧈","🧂","🥫","🍱","🍘",
      "🍙","🍚","🍛","🍜","🍝","🍠","🍢","🍣","🍤","🍥",
      "🥮","🍡","🥟","🥠","🥡","🦀","🦞","🦐","🦑","🦪",
      "🍦","🍧","🍨","🍩","🍪","🎂","🍰","🧁","🥧","🍫",
      "🍬","🍭","🍮","🍯","🍼","🥛","☕","🫖","🍵","🧃",
      "🥤","🧋","🍶","🍺","🍻","🥂","🍷","🥃","🍸","🍹",
      "🧉","🍾","🫗","🥄","🍴","🍽️","🥣","🥡","🥢",
    ],
  },
  {
    name: "Activities",
    icon: "⚽",
    emojis: [
      "⚽","🏀","🏈","⚾","🥎","🎾","🏐","🏉","🥏","🎱",
      "🪀","🏓","🏸","🏒","🏑","🥍","🏏","🪃","🥅","⛳",
      "🪁","🏹","🎣","🤿","🥊","🥋","🎽","🛹","🛼","🛷",
      "⛸️","🥌","🎿","⛷️","🏂","🪂","🏋️","🤼","🤸","⛹️",
      "🤺","🤾","🏌️","🏇","🧘","🏄","🏊","🤽","🚣","🧗",
      "🚴","🚵","🏆","🥇","🥈","🥉","🏅","🎖️","🏵️","🎗️",
      "🎫","🎟️","🎪","🤹","🎭","🩰","🎨","🎬","🎤","🎧",
      "🎼","🎹","🥁","🪘","🎷","🎺","🪗","🎸","🪕","🎻",
      "🎲","♟️","🎯","🎳","🎮","🕹️","🧩","🪄","🎰","🎴",
      "💻","📱","⌨️","🖥️","🖨️","📷","📹","🎥","📺","📻",
    ],
  },
  {
    name: "✨",
    icon: "✨",
    emojis: [
      "🏄",
      "🧘",
      "🏋️",
      "🥋",
      "🏊",
      "✍️",
      "🐶",
      "🐱",
      "🥂",
      "☕",
      "🥙",
      "🎻",
      "🎹",
      "📷",
      "🖥️",
      "❤️",
      "✨",
      "💻"
    ],
  },
  {
    name: "Travel",
    icon: "✈️",
    emojis: [
      "🚗","🚕","🚙","🚌","🚎","🏎️","🚓","🚑","🚒","🚐",
      "🛻","🚚","🚛","🚜","🏍️","🛵","🚲","🛴","🛺","🚔",
      "🚍","🚘","🚖","🛞","🚡","🚠","🚟","🚃","🚋","🚞",
      "🚝","🚄","🚅","🚈","🚂","🚆","🚇","🚊","🚉","✈️",
      "🛫","🛬","🛩️","💺","🛰️","🚀","🛸","🚁","🛶","⛵",
      "🚤","🛥️","🛳️","⛴️","🚢","⚓","🪝","⛽","🚧","🚦",
      "🚥","🚏","🗺️","🗿","🗽","🗼","🏰","🏯","🏟️","🎡",
      "🎢","🎠","⛲","⛱️","🏖️","🏝️","🏜️","🌋","⛰️","🏔️",
      "🗻","🏕️","⛺","🛖","🏠","🏡","🏘️","🏚️","🏗️","🏭",
      "🏢","🏬","🏣","🏤","🏥","🏦","🏨","🏪","🏫","🏩",
    ],
  },
  {
    name: "Objects",
    icon: "💡",
    emojis: [
      "⌚","📱","💻","⌨️","🖥️","🖨️","🖱️","🖲️","💽","💾",
      "💿","📀","📼","📷","📸","📹","🎥","📽️","🎞️","📞",
      "☎️","📟","📠","📺","📻","🎙️","🎚️","🎛️","🧭","⏱️",
      "⏲️","⏰","🕰️","⌛","⏳","📡","🔋","🪫","🔌","💡",
      "🔦","🕯️","🪔","🧯","🛢️","💸","💵","💴","💶","💷",
      "🪙","💰","💳","💎","⚖️","🪜","🧰","🪛","🔧","🔨",
      "⚒️","🛠️","⛏️","🪚","🔩","⚙️","🪤","🧱","⛓️","🧲",
      "🔫","💣","🪓","🔪","🗡️","⚔️","🛡️","🚬","⚰️","🪦",
      "🏺","🔮","📿","🧿","🪬","💈","⚗️","🔭","🔬","🕳️",
      "🩹","🩺","🩻","💊","💉","🩸","🧬","🦠","🧫","🧪",
      "🌡️","🧹","🪠","🧺","🧻","🚽","🚰","🚿","🛁","🛀",
      "🪥","🪒","🧴","🧷","🧹","🧺","🧻","🧼","🫧","🪥",
    ],
  },
  {
    name: "Symbols",
    icon: "❤️",
    emojis: [
      "❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔",
      "❤️‍🔥","❤️‍🩹","❣️","💕","💞","💓","💗","💖","💘","💝",
      "💟","☮️","✝️","☪️","🕉️","☸️","✡️","🔯","🕎","☯️",
      "☦️","🛐","⛎","♈","♉","♊","♋","♌","♍","♎",
      "♏","♐","♑","♒","♓","🆔","⚛️","🉑","☢️","☣️",
      "📴","📳","🈶","🈚","🈸","🈺","🈷️","✴️","🆚","💮",
      "🉐","㊙️","㊗️","🈴","🈵","🈹","🈲","🅰️","🅱️","🆎",
      "🅾️","🆑","🆘","❌","⭕","🛑","⛔","📛","🚫","💯",
      "💢","♨️","🚷","🚯","🚳","🚱","🔞","📵","🚭","❗",
      "❓","‼️","⁉️","🔅","🔆","〽️","⚠️","🚸","🔱","⚜️",
      "🔰","♻️","✅","🈯","💹","❇️","✳️","❎","🌐","💠",
      "Ⓜ️","🌀","💤","🏧","🚾","♿","🅿️","🛗","🈳","🈂️",
      "🛂","🛃","🛄","🛅","🚹","🚺","🚻","🚼","🚮","🎦",
      "📶","🈁","🔣","ℹ️","🔤","🔡","🔠","🆖","🆗","🆙",
      "🆒","🆕","🆓","0️⃣","1️⃣","2️⃣","3️⃣","4️⃣","5️⃣","6️⃣",
      "7️⃣","8️⃣","9️⃣","🔟","🔢","#️⃣","*️⃣","⏏️","▶️","⏸️",
      "⏯️","⏹️","⏺️","⏭️","⏮️","⏩","⏪","⏫","⏬","◀️",
      "🔼","🔽","➡️","⬅️","⬆️","⬇️","↗️","↘️","↙️","↖️",
      "↕️","↔️","↩️","↪️","⤴️","⤵️","🔀","🔁","🔂","🔄",
      "🔃","🎵","🎶","➕","➖","➗","✖️","🟰","♾️","💲",
      "⭐","🌟","💫","✨","☀️","🌤️","⛅","🌥️","☁️","🌦️",
      "🌈","🔥","💧","🌊","🎆","🎇","✨","🎑",
    ],
  },
];

/** 이모지 키워드 맵 — 영어 검색용 */
const emojiKeywords: Record<string, string[]> = {
  // Smileys
  "😀": ["smile", "happy", "grin"],
  "😃": ["smile", "happy", "grin", "big"],
  "😄": ["smile", "happy", "laugh"],
  "😁": ["grin", "beam", "happy"],
  "😆": ["laugh", "happy", "squint"],
  "😅": ["sweat", "nervous", "laugh"],
  "🤣": ["rofl", "laugh", "rolling"],
  "😂": ["laugh", "cry", "tears", "joy"],
  "🙂": ["smile", "slight"],
  "😊": ["blush", "smile", "happy"],
  "😇": ["angel", "innocent", "halo"],
  "🥰": ["love", "hearts", "adore"],
  "😍": ["love", "heart", "eyes"],
  "🤩": ["star", "excited", "starstruck"],
  "😘": ["kiss", "love", "blow"],
  "😎": ["cool", "sunglasses"],
  "🤓": ["nerd", "geek", "glasses"],
  "🥳": ["party", "celebrate", "birthday"],
  "😴": ["sleep", "zzz", "tired", "rest"],
  "🤒": ["sick", "ill", "thermometer"],
  "🤕": ["hurt", "injured", "bandage"],
  "🤢": ["nauseous", "sick", "green"],
  "🤮": ["vomit", "sick", "puke"],
  "😤": ["angry", "huff", "frustrated"],
  "😡": ["angry", "mad", "rage"],
  "😭": ["cry", "sob", "sad", "tears"],
  "😱": ["scream", "scared", "shock"],
  "🥺": ["pleading", "puppy", "cute"],
  "😌": ["relieved", "peaceful", "calm"],

  // People & Gestures
  "👋": ["wave", "hello", "hi", "bye"],
  "👍": ["thumbs up", "good", "like", "yes", "approve"],
  "👎": ["thumbs down", "bad", "dislike", "no"],
  "👏": ["clap", "applause", "bravo"],
  "🙌": ["raise", "hands", "hooray", "celebration"],
  "🤝": ["handshake", "deal", "agreement"],
  "🙏": ["pray", "please", "thanks", "namaste"],
  "💪": ["muscle", "strong", "flex", "strength", "power", "gym"],
  "✍️": ["write", "writing", "pen"],
  "👀": ["eyes", "look", "see", "watch"],
  "🧠": ["brain", "think", "smart", "mind", "study"],

  // Nature
  "🐶": ["dog", "puppy", "pet"],
  "🐱": ["cat", "kitten", "pet"],
  "🐸": ["frog"],
  "🌸": ["cherry", "blossom", "flower", "spring"],
  "🌹": ["rose", "flower", "red", "love"],
  "🌻": ["sunflower", "flower", "sun"],
  "🌞": ["sun", "sunny", "morning"],
  "🌝": ["moon", "night"],
  "🍀": ["clover", "luck", "lucky", "four leaf"],
  "🌿": ["herb", "plant", "leaf", "nature", "green"],
  "🌲": ["tree", "evergreen", "pine", "forest"],
  "🌴": ["palm", "tree", "tropical", "beach", "vacation"],

  // Food & Drink
  "🍇": ["grape", "fruit", "wine"],
  "🍎": ["apple", "red", "fruit"],
  "🍌": ["banana", "fruit"],
  "🍉": ["watermelon", "fruit", "summer"],
  "🍊": ["orange", "fruit", "tangerine"],
  "🍓": ["strawberry", "fruit", "berry"],
  "🍑": ["peach", "fruit"],
  "🥑": ["avocado", "fruit", "healthy"],
  "🍔": ["burger", "hamburger", "fast food", "food"],
  "🍕": ["pizza", "food", "italian"],
  "🍟": ["fries", "french fries", "fast food"],
  "🌮": ["taco", "mexican", "food"],
  "🍣": ["sushi", "japanese", "food", "fish"],
  "🍜": ["noodle", "ramen", "soup", "food", "asian"],
  "🍝": ["pasta", "spaghetti", "food", "italian"],
  "🍛": ["curry", "rice", "food", "indian"],
  "🍚": ["rice", "food", "asian"],
  "🥗": ["salad", "healthy", "food", "vegetable"],
  "🍰": ["cake", "dessert", "sweet", "birthday"],
  "🍩": ["donut", "doughnut", "sweet", "dessert"],
  "🍪": ["cookie", "sweet", "biscuit"],
  "🍫": ["chocolate", "sweet", "candy"],
  "🍦": ["ice cream", "dessert", "sweet"],
  "☕": ["coffee", "cafe", "hot", "drink", "morning"],
  "🍵": ["tea", "green tea", "hot", "drink"],
  "🧋": ["boba", "bubble tea", "drink"],
  "🍺": ["beer", "drink", "alcohol", "pub"],
  "🍻": ["beer", "cheers", "drink", "alcohol", "pub"],
  "🍷": ["wine", "drink", "alcohol", "red wine"],
  "🍸": ["cocktail", "martini", "drink", "alcohol"],
  "🍹": ["tropical", "drink", "cocktail", "alcohol"],
  "🥃": ["whiskey", "drink", "alcohol", "bourbon"],
  "🍾": ["champagne", "celebrate", "drink", "party"],
  "🥛": ["milk", "drink"],
  "🧃": ["juice", "drink", "box"],
  "🥤": ["cup", "drink", "soda"],
  "🍼": ["baby", "bottle", "milk"],

  // Activities & Sports
  "⚽": ["soccer", "football", "sport", "ball"],
  "🏀": ["basketball", "sport", "ball"],
  "🏈": ["football", "american", "sport"],
  "⚾": ["baseball", "sport", "ball"],
  "🎾": ["tennis", "sport", "ball", "racket"],
  "🏐": ["volleyball", "sport", "ball"],
  "🏓": ["ping pong", "table tennis", "sport"],
  "🏸": ["badminton", "sport", "shuttlecock"],
  "🥊": ["boxing", "sport", "fight", "punch"],
  "🥋": ["martial arts", "karate", "judo", "taekwondo", "sport"],
  "🏋️": ["gym", "weight", "lift", "exercise", "fitness", "workout", "strength"],
  "🤸": ["gymnastics", "tumble", "sport", "acrobat"],
  "🧘": ["yoga", "meditation", "zen", "stretch", "relax", "mindfulness"],
  "🏄": ["surf", "surfing", "wave", "beach", "sport"],
  "🏊": ["swim", "swimming", "pool", "sport", "water"],
  "🚴": ["bike", "bicycle", "cycling", "ride", "sport"],
  "🚵": ["mountain bike", "cycling", "off road"],
  "🏃": ["run", "running", "jog", "sprint", "exercise"],
  "🏆": ["trophy", "winner", "champion", "award", "win"],
  "🥇": ["gold", "medal", "first", "winner"],
  "🎨": ["art", "paint", "palette", "creative", "draw", "design"],
  "🎬": ["movie", "film", "cinema", "video", "director"],
  "🎤": ["microphone", "sing", "karaoke", "music", "vocal"],
  "🎧": ["headphone", "music", "listen", "audio", "podcast"],
  "🎹": ["piano", "keyboard", "music", "play"],
  "🎸": ["guitar", "music", "rock", "play"],
  "🎻": ["violin", "music", "classical"],
  "🥁": ["drum", "music", "beat"],
  "🎮": ["game", "gaming", "video game", "play", "controller"],
  "🕹️": ["joystick", "game", "arcade"],
  "🧩": ["puzzle", "jigsaw", "solve"],
  "🎯": ["target", "bullseye", "goal", "dart", "aim", "focus"],
  "🎳": ["bowling", "sport", "ball"],
  "🎲": ["dice", "game", "luck", "random"],

  // Tech & Work
  "💻": ["computer", "laptop", "code", "coding", "work", "programming", "dev"],
  "📱": ["phone", "mobile", "smartphone", "cell"],
  "⌨️": ["keyboard", "type", "typing", "computer"],
  "🖥️": ["desktop", "monitor", "screen", "computer"],
  "🖨️": ["printer", "print"],
  "📷": ["camera", "photo", "picture"],
  "📹": ["video", "camera", "record", "film"],
  "📺": ["tv", "television", "watch", "screen"],
  "📻": ["radio", "music", "broadcast"],
  "🔋": ["battery", "power", "charge", "energy"],
  "💡": ["idea", "light", "bulb", "bright", "think"],

  // Travel & Transport
  "🚗": ["car", "drive", "auto", "vehicle"],
  "🚕": ["taxi", "cab", "ride"],
  "🚌": ["bus", "transit", "public"],
  "🚂": ["train", "locomotive", "travel"],
  "✈️": ["plane", "airplane", "fly", "travel", "flight"],
  "🚀": ["rocket", "space", "launch", "fast"],
  "🛸": ["ufo", "alien", "space"],
  "🚲": ["bicycle", "bike", "ride", "cycling"],
  "🏠": ["home", "house"],
  "🏢": ["office", "building", "work", "company"],
  "🏥": ["hospital", "medical", "health"],
  "🏫": ["school", "education", "university", "college", "study"],
  "🏖️": ["beach", "vacation", "holiday", "sea"],
  "⛰️": ["mountain", "hike", "climb", "nature"],
  "🏕️": ["camp", "camping", "tent", "outdoor"],

  // Objects & Tools
  "📚": ["book", "books", "read", "reading", "study", "library", "learn"],
  "📖": ["book", "open", "read", "reading"],
  "📝": ["memo", "note", "write", "writing", "pen", "pencil"],
  "📓": ["notebook", "journal", "diary", "write"],
  "📋": ["clipboard", "list", "task", "todo"],
  "✏️": ["pencil", "write", "draw", "edit"],
  "🖊️": ["pen", "write", "ink"],
  "📎": ["paperclip", "attach", "clip"],
  "📌": ["pin", "pushpin", "location", "mark"],
  "📅": ["calendar", "date", "schedule", "plan"],
  "⏰": ["alarm", "clock", "time", "wake"],
  "⏱️": ["stopwatch", "timer", "time"],
  "🔔": ["bell", "notification", "alert", "ring"],
  "🔑": ["key", "lock", "password", "security"],
  "💰": ["money", "bag", "rich", "cash"],
  "💳": ["credit card", "payment", "buy", "pay"],
  "💎": ["diamond", "gem", "jewel", "precious"],
  "🔧": ["wrench", "tool", "fix", "repair"],
  "🔨": ["hammer", "tool", "build", "construct"],
  "⚙️": ["gear", "settings", "cog", "mechanic"],
  "🧰": ["toolbox", "tools", "fix", "repair"],
  "💊": ["pill", "medicine", "drug", "health"],
  "💉": ["syringe", "injection", "vaccine", "medical"],
  "🩺": ["stethoscope", "doctor", "medical", "health"],
  "🧹": ["broom", "clean", "sweep"],
  "🧺": ["basket", "laundry"],
  "🛁": ["bath", "bathtub", "relax", "clean"],
  "🛏️": ["bed", "sleep", "rest"],
  "🪥": ["toothbrush", "teeth", "dental", "hygiene"],
  "🧴": ["lotion", "skincare", "beauty", "moisturizer"],

  // Symbols & Misc
  "❤️": ["heart", "love", "red"],
  "🧡": ["heart", "orange", "love"],
  "💛": ["heart", "yellow", "love"],
  "💚": ["heart", "green", "love"],
  "💙": ["heart", "blue", "love"],
  "💜": ["heart", "purple", "love"],
  "🖤": ["heart", "black", "love"],
  "🤍": ["heart", "white", "love"],
  "💯": ["hundred", "perfect", "score", "100"],
  "🔥": ["fire", "hot", "flame", "lit"],
  "✨": ["sparkle", "star", "shine", "magic", "clean"],
  "⭐": ["star", "favorite", "rating", "gold"],
  "🌟": ["star", "glow", "bright", "shine"],
  "🌈": ["rainbow", "color", "pride"],
  "💧": ["water", "drop", "rain", "tear"],
  "🌊": ["wave", "ocean", "sea", "water", "beach"],
  "☀️": ["sun", "sunny", "bright", "weather", "day"],
  "🌙": ["moon", "night", "crescent", "sleep"],
  "⚡": ["lightning", "bolt", "electric", "energy", "power", "fast"],
  "❄️": ["snow", "cold", "winter", "freeze"],
  "✅": ["check", "done", "complete", "yes", "correct"],
  "❌": ["cross", "no", "wrong", "cancel", "delete"],
  "⚠️": ["warning", "caution", "alert", "danger"],
  "🔕": ["bell", "notification", "alert"],
  "🎵": ["music", "note", "song"],
  "🎶": ["music", "notes", "song", "melody"],

  // Additional common use
  "🔆": ["bright", "brightness", "sun", "light"],
  "🕍": ["synagogue", "temple", "religion", "pray", "church"],
  "🗓️": ["calendar", "date", "schedule"],
  "🛒": ["shopping", "cart", "buy", "grocery"],
  "🎁": ["gift", "present", "birthday", "surprise"],
  "🎉": ["party", "celebration", "confetti", "congrats"],
  "🎊": ["party", "confetti", "celebration"],
  "🏋️‍♀️": ["gym", "weight", "lift", "exercise", "woman"],
  "🏋️‍♂️": ["gym", "weight", "lift", "exercise", "man"],
  "🧑‍💻": ["developer", "coder", "programmer", "tech", "computer"],
  "👨‍💻": ["developer", "coder", "programmer", "man", "tech"],
  "👩‍💻": ["developer", "coder", "programmer", "woman", "tech"],
  "👨‍🍳": ["chef", "cook", "food", "man"],
  "👩‍🍳": ["chef", "cook", "food", "woman"],
  "👨‍🎓": ["graduate", "student", "education", "man"],
  "👩‍🎓": ["graduate", "student", "education", "woman"],
  "👨‍⚕️": ["doctor", "medical", "health", "man"],
  "👩‍⚕️": ["doctor", "medical", "health", "woman"],
  "🧑‍🏫": ["teacher", "professor", "education"],
  "💤": ["sleep", "zzz", "rest", "nap", "tired"],
  "🚶": ["walk", "walking", "person", "pedestrian"],
  "🏃‍♂️": ["run", "running", "man", "jog"],
  "🏃‍♀️": ["run", "running", "woman", "jog"],
};

/** 키워드 기반 이모지 검색 */
export function searchEmojis(query: string): string[] {
  const lower = query.toLowerCase().trim();
  if (!lower) return [];

  const results: string[] = [];

  // 1) 키워드 맵에서 검색
  for (const [emoji, keywords] of Object.entries(emojiKeywords)) {
    if (keywords.some((kw) => kw.includes(lower))) {
      results.push(emoji);
    }
  }

  // 2) 키워드 맵에 없는 이모지도 query가 이모지 자체와 일치하면 포함
  if (results.length === 0) {
    for (const cat of emojiCategories) {
      for (const em of cat.emojis) {
        if (em.includes(lower)) results.push(em);
      }
    }
  }

  // 중복 제거
  return [...new Set(results)];
}
